### ISSUE TITLE
Work on UI fixation for the native app (Mobile browser / iPad)

### ISSUE THREAD

**Issue by ko-watanabe** [ko-watanabe/ko-watanabe.github.io#3]
# Description
The current version only focuses on a web browser.
Need to fix or apply for the UI of native applications.

# TODO
- [ ] Design for the native application.
- [ ] Apply the design.
- [ ] Check in each device.
