### ISSUE TITLE
Make experience and publication page structured/organized.

### ISSUE THREAD

**Issue by ko-watanabe** [ko-watanabe/ko-watanabe.github.io#5]
# Description
- Currently, the code is all written directly into HTML.
- Make another directory for the experience or publication and use `index.html` to read and show.

# TODO
- [ ] Add another directory, `source/citation`.
- [ ] Put all the information away from the current `index.html`.
- [ ] Check on each browser/native page.
